import 'package:drift/drift.dart';
import 'package:json_annotation/json_annotation.dart';

part 'recipe.g.dart';
 // Generated by build_runner

// TODO: Annotate with @JsonSerializable for JSON serialization
// TODO: Annotate with @DriftDatabase for database table definition

@JsonSerializable()
@DataClassName('RecipeData')
class Recipes extends Table {
  @override
  String get tableName => 'recipes';

  TextColumn get id => text().customConstraint('UNIQUE')();
  TextColumn get title => text().withLength(min: 1, max: 100)();
  TextColumn get language => text().withLength(max: 5)();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDate)();
  DateTimeColumn get updatedAt => dateTime().withDefault(currentDate)();
  BoolColumn get isDeleted => boolean().withDefault(const Constant(false))();

  TextColumn get ingredients => text().nullable()();
  TextColumn get steps => text().nullable()();
  TextColumn get notes => text().nullable()();

  TextColumn get categoriesJson => text().nullable()();
  TextColumn get tagsJson => text().nullable()();
  TextColumn get cuisine => text().nullable()();

  TextColumn get youtubeUrl => text().nullable()();

  TextColumn get ownerId => text().nullable()();
  BoolColumn get isShared => boolean().withDefault(const Constant(false))();
  TextColumn get sharedWithGroupIdsJson => text().nullable()();
  @override
  Set<Column> get primaryKey => {id};
}

// Helper methods for JSON serialization/deserialization will be handled by json_serializable
// and custom converters for Drift. For now, these are just placeholders.
